### ISSUE TITLE
Interpretration of report progress

### ISSUE THREAD

**Issue by felloumi** [rstudio/shinycannon#21]
Hello,

I run the load test for my shiny app using the shinycannon command-line tool. I got results however looking at the progress report I found errors and many failures. Here below my progress report. I will appreciate your help understanding the errors and failures. I can generate the html report and I wonder if it is a valid one?

Thanks!

>>
**shinycannon recording.log http://...../ --workers 1 --loaded-duration-minutes 10 --output-dir run1**
>>

2018-10-29 12:20:26.368 INFO [thread01] - Warming up
2018-10-29 12:20:26.368 INFO [progress] - Running: 0, Failed: 0, Done: 0
2018-10-29 12:20:26.368 INFO [thread00] - Waiting for warmup to complete
2018-10-29 12:20:26.369 INFO [thread00] - Maintaining for 10 minutes (600000 ms)
2018-10-29 12:20:31.370 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:20:36.371 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:20:41.373 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:20:46.378 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:20:51.380 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:20:56.384 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:01.384 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:06.387 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:11.387 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:16.388 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:21.390 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:26.393 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:31.396 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:36.398 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:41.402 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:46.402 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:51.402 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:21:56.403 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:01.403 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:06.403 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:11.407 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:16.408 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:21.408 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:26.410 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:31.415 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:36.415 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:41.415 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:46.416 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:51.421 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:22:56.422 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:01.424 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:06.424 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:11.428 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:16.430 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:21.432 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:26.436 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:31.436 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:36.438 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:41.438 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:46.443 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:51.447 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:23:56.447 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:01.447 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:06.449 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:11.449 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:16.449 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:21.451 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:26.452 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:31.457 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:36.459 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:41.460 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:46.464 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:51.465 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:24:56.465 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:25:01.465 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:25:06.467 INFO [progress] - Running: 1, Failed: 0, Done: 0
2018-10-29 12:25:07.980 WARN [thread01] - WS_RECV line 184: Haven't received message after 30 seconds
2018-10-29 12:25:11.468 INFO [progress] - Running: 1, Failed: 0, Done: 0
**2018-10-29 12:25:15.051 ERROR [thread01] - Playback failed: Entity may not be null
java.lang.IllegalArgumentException: Entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)2018-10-29 12:25:15.058 INFO [thread01] - Running again**
**2018-10-29 12:25:16.469 INFO [progress] - Running: 1, Failed: 1, Done: 0**
2018-10-29 12:25:21.469 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:26.469 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:31.474 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:36.478 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:41.481 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:46.485 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:51.488 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:25:56.488 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:01.488 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:06.488 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:11.488 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:16.491 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:21.493 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:26.497 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:31.503 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:36.503 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:41.503 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:46.503 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:51.504 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:26:56.505 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:01.506 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:06.507 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:11.510 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:16.510 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:21.511 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:26.512 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:31.516 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:36.519 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:41.520 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:46.523 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:51.523 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:27:56.525 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:01.529 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:06.532 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:11.532 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:16.532 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:21.535 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:26.536 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:31.540 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:36.541 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:41.542 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:46.542 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:51.545 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:28:56.548 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:01.548 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:06.549 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:11.550 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:16.550 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:21.554 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:26.559 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:31.564 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:36.568 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:41.569 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:43.683 WARN [thread01] - WS_RECV line 184: Haven't received message after 30 seconds
2018-10-29 12:29:46.570 INFO [progress] - Running: 1, Failed: 1, Done: 0
2018-10-29 12:29:51.571 INFO [progress] - Running: 1, Failed: 1, Done: 0
**2018-10-29 12:29:52.104 ERROR [thread01] - Playback failed: Entity may not be null
java.lang.IllegalArgumentException: Entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)2018-10-29 12:29:52.104 INFO [thread01] - Running again**
**2018-10-29 12:29:56.572 INFO [progress] - Running: 1, Failed: 2, Done: 0**
2018-10-29 12:30:01.575 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:06.575 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:11.575 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:16.576 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:21.576 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:26.373 INFO [thread00] - Stopped maintaining, waiting for workers to stop
2018-10-29 12:30:26.576 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:31.581 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:36.582 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:41.582 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:46.583 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:51.587 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:30:56.587 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:01.590 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:06.591 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:11.592 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:16.595 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:21.598 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:26.599 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:31.599 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:36.602 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:41.605 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:46.605 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:51.606 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:31:56.606 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:01.606 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:06.606 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:11.607 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:16.607 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:21.611 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:26.611 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:31.615 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:36.617 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:41.617 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:46.617 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:51.622 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:32:56.626 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:01.629 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:06.632 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:11.632 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:16.638 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:21.641 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:26.646 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:31.649 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:36.649 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:41.651 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:46.652 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:51.657 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:33:56.658 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:01.661 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:06.666 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:11.667 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:16.672 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:19.538 WARN [thread01] - WS_RECV line 184: Haven't received message after 30 seconds
2018-10-29 12:34:21.672 INFO [progress] - Running: 1, Failed: 2, Done: 0
2018-10-29 12:34:26.674 INFO [progress] - Running: 1, Failed: 2, Done: 0
**2018-10-29 12:34:27.565 ERROR [thread01] - Playback failed: Entity may not be null
java.lang.IllegalArgumentException: Entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)2018-10-29 12:34:27.565 INFO [thread01] - Stopped
2018-10-29 12:34:27.565 INFO [thread00] - Complete. Failed: 3, Done: 0**

**Comment by alandipert** [comment]
Hi @felloumi, those errors indicate an exception was thrown somewhere in the Kotlin code. In particular, it looks like the exception is coming from Apache HttpClient (org.apache.http), which is the HTTP client we use.

My guess about why this is happening is that in the code, we use a convenience method, `EntityUtils.toString`, to convert an HTTP response body to a String. I think that sometimes your server is not completing the response, or otherwise returning an empty response, and so the `response.entity` passed to `EntityUtils.toString` is null.

I haven't see this problem before, but I'm surprised you see it considering you have `--workers 1`. Usually, we only see errors like these (caused by web server dropping the request) at high concurrency.

To get more information on the error, you can run this command instead:
```
shinycannon recording.log http://...../ --workers 1 --loaded-duration-minutes 10 --output-dir run1 --debug-log
```

That will cause an *extremely verbose* log called `run1/debug.log` to be produced. By searching that log for the error message "Entity may not be null" you should be able to find a full stack trace that could provide additional information.

If you can share what you find, I'd be happy to take a look.

Something else to look at is the load on your server during the test. Is it extremely high? If you visit the target application yourself during the test, is it very sluggish?

**Comment by felloumi** [comment]
Hi Alan,

The file is huge. Here is a portion:
>>
....
2019-01-17 17:13:52.149 DEBUG [thread01] - http-outgoing-84 << HTTP/1.1 204 No Content
2019-01-17 17:13:52.149 DEBUG [thread01] - http-outgoing-84 << X-Powered-By: Shiny Server Pro
2019-01-17 17:13:52.149 DEBUG [thread01] - http-outgoing-84 << Date: Thu, 17 Jan 2019 22:13:52 GMT
2019-01-17 17:13:52.149 DEBUG [thread01] - http-outgoing-84 << Connection: keep-alive
2019-01-17 17:13:52.149 DEBUG [thread01] - Connection can be kept alive indefinitely
2019-01-17 17:13:52.149 DEBUG [thread01] - Connection [id: 84][route: {}->http://...:3838] can be kept alive indefinitely
2019-01-17 17:13:52.149 DEBUG [thread01] - http-outgoing-84: set socket timeout to 0
2019-01-17 17:13:52.149 DEBUG [thread01] - Connection released: [id: 84][route: {}->http://....:3838][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
2019-01-17 17:13:52.149 ERROR [thread01] - Playback failed: Entity may not be null
java.lang.IllegalArgumentException: Entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:307)
	at com.rstudio.shinycannon.Event$Http$REQ_POST$handle$1.invoke(Events.kt:236)
	at com.rstudio.shinycannon.Event$Http$REQ_POST$handle$1.invoke(Events.kt:206)
	at com.rstudio.shinycannon.Event.withLog(Events.kt:71)
	at com.rstudio.shinycannon.Event$Http$REQ_POST.handle(Events.kt:212)
	at com.rstudio.shinycannon.ShinySession.run(Main.kt:195)
	at com.rstudio.shinycannon.EnduranceTest$run$4.invoke(Main.kt:299)
	at com.rstudio.shinycannon.EnduranceTest$run$4.invoke$default(Main.kt:291)
	at com.rstudio.shinycannon.EnduranceTest$run$6.invoke(Main.kt:322)
	at com.rstudio.shinycannon.EnduranceTest$run$6.invoke(Main.kt:259)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2019-01-17 17:13:52.150 INFO [thread01] - Running again
.....
>>
Please let me know if you need the whole file and thanks for your help.

@felloumi

**Comment by felloumi** [comment]
Forgot to mention that I was able to generate a report. Are the results considered valid?
