### ISSUE TITLE
Explanation for "Tried to WS_OPEN but already have a websocket"

### ISSUE THREAD

**Issue by antpingelli** [rstudio/shinycannon#52]
When running `shinycannon recording.log https://example.com/ --workers 5 --loaded-duration-minutes 2 --output-dir run1 --overwrite-output` I am consistently seeing the error `Tried to WS_OPEN but already have a websocket`, below is the beginning of the ouput 

> 2020-08-03 16:13:29.113 INFO [thread00] - Detected target application type: RStudio Server Connect
2020-08-03 16:13:29.116 INFO [progress] - Running: 0, Failed: 0, Done: 0
2020-08-03 16:13:29.116 INFO [thread01] - Warming up
2020-08-03 16:13:29.117 INFO [thread00] - Waiting for warmup to complete
2020-08-03 16:13:34.120 INFO [progress] - Running: 1, Failed: 0, Done: 0
2020-08-03 16:13:39.122 INFO [progress] - Running: 1, Failed: 0, Done: 0
2020-08-03 16:13:39.178 INFO [thread02] - Warming up
2020-08-03 16:13:39.436 ERROR [thread01] - Playback failed: Tried to WS_OPEN but already have a websocket
java.lang.IllegalStateException: Tried to WS_OPEN but already have a websocket
	at com.rstudio.shinycannon.Event$WS_OPEN.handle(Events.kt:255)2020-08-03 16:13:39.437 INFO [thread01] - Running again
2020-08-03 16:13:44.127 INFO [progress] - Running: 2, Failed: 1, Done: 0
2020-08-03 16:13:49.127 INFO [progress] - Running: 2, Failed: 1, Done: 0
2020-08-03 16:13:49.244 INFO [thread03] - Warming up
2020-08-03 16:13:49.537 ERROR [thread02] - Playback failed: Tried to WS_OPEN but already have a websocket
java.lang.IllegalStateException: Tried to WS_OPEN but already have a websocket
	at com.rstudio.shinycannon.Event$WS_OPEN.handle(Events.kt:255)2020-08-03 16:13:49.537 INFO [thread02] - Running again
2020-08-03 16:13:49.652 ERROR [thread01] - Playback failed: Tried to WS_OPEN but already have a websocket
java.lang.IllegalStateException: Tried to WS_OPEN but already have a websocket
	at com.rstudio.shinycannon.Event$WS_OPEN.handle(Events.kt:255)2020-08-03 16:13:49.653 INFO [thread01] - Running again

It looks to be coming from here https://github.com/rstudio/shinycannon/blob/a581ed7a223fc6cf4e8e96084fe3cdb0f7711446/src/main/kotlin/com/rstudio/shinycannon/Events.kt#L255
is there any guidance on how to solve this issue? Thanks!

**Comment by jcheng5** [comment]
Thanks for the report and sorry for the delay!

Based on the additional data you emailed to support, it looks to me like shinycannon has a conflict with the brand new `options(shiny.autoreload=TRUE)` option, which I assume your app turns on. It's a good idea to remove this option from deployed apps anyway, they'll just be wasting resources. Or you could do something like `options(shiny.autoreload=interactive())` which means turn on autoreload only if the current R session is an interactive one. I'll file a separate issue for the incompatibility so you're not bothered with notifications.

**Comment by jcheng5** [comment]
I'll very confident this is it so I'll close this issue now--if it turns out this isn't the issue, let me know and I'll reopen.

**Comment by antpingelli** [comment]
Hey Joe! We have wanted to use shinnycannon to load test our apps because they have been taking over 20 seconds to load on our Connect server, turns out the reason they were taking so long was because of the auto reload as well! We are now seeing sub 5 second load times, thank you so much that helped tremendously.
